openapi: 3.1.1
info:
  title: AlphaForge Cryptocurrency Microstructure Implementation
  version: "0.4.0"
  description: |
    Machine-readable implementation tracking for cryptocurrency microstructure integration
    with community-proven alpha factor analysis frameworks in AlphaForge quantitative finance codebase
  contact:
    name: Implementation Tracking System

components:
  schemas:
    TemporalViolation:
      type: object
      properties:
        id:
          type: string
        severity:
          type: string
          enum: [critical, high, medium, low]
        status:
          type: string
          enum: [identified, in-progress, resolved, validated]
        file_path:
          type: string
        line_number:
          type: integer
        violation_type:
          type: string
        description:
          type: string
        remediation_action:
          type: string
        sota_replacement:
          type: string
          nullable: true

    SOTAFramework:
      type: object
      properties:
        current_implementation:
          type: string
        replacement_framework:
          type: string
        justification:
          type: string
        migration_status:
          type: string
          enum: [planned, in-progress, completed, validated]

paths:
  /violations/temporal:
    get:
      summary: Critical temporal violations tracking
      responses:
        '200':
          description: Current status of temporal violations
          content:
            application/yaml:
              schema:
                type: object
                properties:
                  violations:
                    type: array
                    items:
                      $ref: '#/components/schemas/TemporalViolation'

# CRITICAL TEMPORAL VIOLATIONS
temporal_violations:
  - id: TV-001
    severity: critical
    status: resolved
    file_path: alphagen_generic/features.py
    line_number: 14
    violation_type: look_ahead_bias
    description: "Original: target = Ref(vwap,-21)/Ref(vwap,-1)-1 used future VWAP data"
    remediation_action: "Fixed: target = Ref(vwap, 1) / vwap - 1 uses historical data only"
    sota_replacement: null
    resolution_date: "2025-01-17"

  - id: TV-002
    severity: critical
    status: identified
    file_path: exp_ML_train_and_result.ipynb
    line_number: 41
    violation_type: look_ahead_bias
    description: "tmp = (vwap_unstack.shift(-21)/vwap_unstack.shift(-1))-1 uses future data"
    remediation_action: "Implement proper temporal feature engineering with historical data only"
    sota_replacement: "feature-engine library for automated temporal-safe feature creation"

  - id: TV-003
    severity: critical
    status: identified
    file_path: gplearn/tests/test_examples.py
    line_number: 183
    violation_type: temporal_scaling_violation
    description: "X = StandardScaler().fit_transform(X) uses global scaling with future data"
    remediation_action: "Implement per-fold scaling with TimeSeriesSplit"
    sota_replacement: "sklearn.model_selection.TimeSeriesSplit with Pipeline"

# UNDEFINED VARIABLE ERRORS
undefined_variable_errors:
  - id: UE-001
    severity: critical
    status: resolved
    file_path: train_RL.py
    line_number: 140
    description: "NameError: name 'target' is not defined"
    remediation_action: "Fixed by correcting target definition in alphagen_generic/features.py"
    resolution_date: "2025-01-17"

  - id: UE-002
    severity: critical
    status: resolved
    file_path: train_GP.py
    line_number: 143
    description: "NameError: name 'target' is not defined"
    remediation_action: "Fixed by correcting target definition in alphagen_generic/features.py"
    resolution_date: "2025-01-17"

  - id: UE-003
    severity: critical
    status: resolved
    file_path: train_AFF.py
    line_number: 169
    description: "NameError: name 'target' is not defined"
    remediation_action: "Fixed by correcting target definition in alphagen_generic/features.py"
    resolution_date: "2025-01-17"

  - id: UE-004
    severity: critical
    status: identified
    file_path: train_DSO.py
    line_number: 41
    description: "NameError: name 'target' is not defined - BLOCKED by numba dependency issue"
    remediation_action: "Cannot test due to numba Python 3.13 incompatibility"

# DEPENDENCY COMPATIBILITY ISSUES
dependency_issues:
  - id: DI-001
    severity: high
    status: resolved
    dependency: numba
    file_path: dso/subroutines.py
    line_number: 3
    description: "numba only supports Python >=3.6,<3.10, but using Python 3.13"
    remediation_action: "Fixed: numba 0.62.0rc2 now supports Python 3.13"
    blocking: []
    resolution_date: "2025-01-17"

  - id: DI-002
    severity: medium
    status: identified
    dependency: tensorflow-metal
    file_path: N/A
    line_number: N/A
    description: "tensorflow-metal 1.2.0 only supports Python 3.9-3.12, not Python 3.13"
    remediation_action: "Metal GPU acceleration unavailable until tensorflow-metal adds Python 3.13 support"
    blocking: []
    workaround: "PyTorch MPS backend available for GPU acceleration"

# SOTA FRAMEWORK REPLACEMENTS
sota_replacements:
  - id: SF-001
    current_implementation: "OpenAI Gym (deprecated)"
    replacement_framework: "Gymnasium"
    justification: "Maintained fork with NumPy 2.0 support and active development"
    migration_status: completed
    files_affected: [train_RL.py, alphagen/rl/env/wrapper.py]

  - id: SF-006
    current_implementation: "Custom alpha factor evaluation"
    replacement_framework: "Alphalens-reloaded"
    justification: "Community-proven framework with industry-standard metrics and tear sheets"
    migration_status: completed
    files_affected: [alphagen_qlib/alphalens_integration.py]

  - id: SF-007
    current_implementation: "Synthetic cryptocurrency data"
    replacement_framework: "gapless-crypto-data"
    justification: "Authentic Binance market data with zero-gap historical coverage"
    migration_status: completed
    files_affected: [alphagen_qlib/crypto_data.py]

  - id: SF-008
    current_implementation: "Basic OHLCV features (6 columns)"
    replacement_framework: "Microstructure indicators (31 columns)"
    justification: "Comprehensive order flow analysis with rolling statistics and z-score normalization"
    migration_status: completed
    files_affected: [alphagen_qlib/crypto_data.py]

  - id: SF-002
    current_implementation: "Custom Genetic Programming"
    replacement_framework: "DEAP (Distributed Evolutionary Algorithms in Python)"
    justification: "Industry-standard GP framework with proven scalability"
    migration_status: planned
    files_affected: [train_GP.py, gplearn/]

  - id: SF-003
    current_implementation: "Custom backtesting logic"
    replacement_framework: "backtesting.py"
    justification: "Validated framework with temporal safeguards and standard metrics"
    migration_status: planned
    files_affected: [combine_AFF.py, train_AFF.py]

  - id: SF-005
    current_implementation: "Custom entropy calculations"
    replacement_framework: "InfoMeasure + JAX"
    justification: "SOTA 2024-2025 entropy stack with 35x GPU speedup"
    migration_status: planned
    files_affected: [alphagen/models/alpha_pool.py]

# IMPLEMENTATION PHASES
implementation_phases:
  phase_1_critical:
    priority: 1
    description: "Stop all training - fix temporal violations"
    items:
      - TV-001
      - TV-002
      - TV-003
      - UE-001
      - UE-002
      - UE-003
      - UE-004

  phase_2_framework_upgrades:
    priority: 2
    description: "Replace deprecated/custom implementations with SOTA"
    items:
      - SF-001
      - SF-002
      - SF-003

  phase_3_optimization:
    priority: 3
    description: "Performance and automation improvements"
    items:
      - SF-004
      - SF-005

# VALIDATION CRITERIA
validation_criteria:
  temporal_integrity:
    - no_future_data_access
    - proper_train_test_split
    - per_fold_scaling_only
    - exception_only_failures

  framework_compatibility:
    - backward_compatibility_maintained
    - performance_improvement_validated
    - documentation_updated
    - tests_passing

microstructure_integration:
  - id: MI-001
    component: "11-column crypto data utilization"
    status: completed
    implementation: "alphagen_qlib/crypto_data.py"
    features:
      base_ohlcv: ["open", "high", "low", "close", "volume"]
      microstructure: ["close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume"]
      derived: ["vwap", "returns", "log_returns", "volatility"]
      order_flow: ["order_flow_imbalance", "quote_flow_imbalance", "taker_pressure"]
      market_activity: ["avg_trade_size", "trade_intensity", "price_spread_ratio", "volume_concentration"]
      rolling_stats: ["rolling_mean", "rolling_std", "zscore_normalization"]

  - id: MI-002
    component: "Alphalens framework integration"
    status: completed
    implementation: "alphagen_qlib/alphalens_integration.py"
    capabilities:
      - information_coefficient_analysis
      - quantile_performance_evaluation
      - turnover_analysis
      - tear_sheet_generation
      - multi_factor_comparison

  - id: MI-003
    component: "Community-proven algorithms adoption"
    status: completed
    replacements:
      custom_alpha_evaluation: "alphalens-reloaded"
      synthetic_data: "gapless-crypto-data"
      basic_features: "microstructure_indicators"

validation_results:
  test_microstructure_integration:
    data_loading: "passed"
    feature_generation: "31_columns_operational"
    alphalens_framework: "integrated"
    correlation_analysis: "passed"
    performance_metrics: "13_microstructure_features_validated"

  test_crypto_integration:
    real_data_loading: "passed"
    expression_evaluation: "functional"
    data_variance: "realistic_crypto_pricing"
    zero_synthetic_data: "confirmed"

metadata:
  created: "2025-01-17"
  last_updated: "2025-09-17"
  version: "0.4.0"
  tracking_format: "OpenAPI 3.1.1"
  microstructure_implementation: "completed"
  community_algorithms: "integrated"
  git_lfs_configured: true